Repository WildCodeSchool/orleans-php-202103-project-haras, pull requests merged in 2021-04, with the labels that each got.

#3 First init
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#7 add logo_favicon
  public/assets/images/logo_favicon.png
  src/View/layout.html.twig
Labels: Reviewed

#4 S01us03 admin navbar
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/logo_min.png
  src/Controller/AdminController.php
  src/View/Admin/Includes/_navbar.html.twig
  src/View/Admin/course.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Question answered, Reviewed

#11 add navbar-user
  public/assets/css/navbar.css
  src/View/Includes/_navbar.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#9 S01 us11 onglets cours
  public/assets/css/course.css
  public/assets/css/course_tab.css
  src/Controller/CourseController.php
  src/View/User/Includes/_course_tab.html.twig
  src/View/User/course.html.twig
Labels: Corrections done, Reviewed

#14 US03-03: googlemap page Haras
  public/assets/css/haras.css
  public/assets/css/haras_googlemap.css
  src/Controller/HarasController.php
  src/View/User/Includes/_haras_googlemap.html.twig
  src/View/User/haras.html.twig
Labels: Corrections done, Reviewed

#20 S02us01 02 layaout banner
  public/assets/css/banner.css
  public/assets/css/style.css
  public/assets/images/collector.webp
  src/View/Includes/_banner.html.twig
Labels: Corrections done, Reviewed

#28 S02us01 03 button to go up
  src/View/Includes/_button_to_go_up.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#24 S02-01: Background Carousel with Card Presentation
  public/assets/css/welcome.css
  public/assets/images/image1.webp
  public/assets/images/image2.jpg
  public/assets/images/image3.jpg
  public/assets/images/image4.jpg
  public/assets/images/image5.jpg
  src/Controller/WelcomeController.php
  src/View/User/Includes/_welcome_background_slideshow.html.twig
  src/View/User/welcome.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#17 add footer
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/bgfooter.png
  public/assets/images/emailharas.png
  public/assets/images/telharas.png
  src/View/Includes/_footer.html.twig
  src/View/layout.html.twig
Labels: Changes requested

#37 use block empty for the moment
  src/View/User/welcome.html.twig
Labels: Reviewed

#39 add white block in course page
  public/assets/css/course.css
  public/assets/css/course_white_block.css
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/course.html.twig
Labels: Reviewed

#38 Add white block in haras page
  public/assets/css/haras.css
  public/assets/css/haras_white_block.css
  src/View/User/Includes/_haras_white_block.html.twig
  src/View/User/haras.html.twig
Labels: Reviewed

#31 US03-01: add grey block in haras page
  public/assets/css/haras.css
  public/assets/css/haras_grey_block.css
  src/View/User/Includes/_haras_grey_block.html.twig
  src/View/User/haras.html.twig
Labels: Conflicts Resolved, Reviewed

#46 Contact page with googlemap
  public/assets/css/contact.css
  public/assets/css/contact_googlemap.css
  src/Controller/ContactController.php
  src/View/User/Includes/_contact_googlemap.html.twig
  src/View/User/contact.html.twig
Labels: Reviewed

#33 add grey block in stage page
  public/assets/css/stage.css
  public/assets/css/stage_grey_block.css
  src/Controller/StageController.php
  src/View/User/Includes/_stage_grey_block.html.twig
  src/View/User/stage.html.twig
Labels: Corrections done, Reviewed

#35 render change
  .gitignore
  src/Controller/WelcomeController.php
  src/View/Home/index.html.twig
  src/View/User/welcome.html.twig
Labels: Resolved conflict, Reviewed

#30 US01-04 Carousel
  public/assets/css/carousel.css
  public/assets/css/course.css
  public/assets/images/accueil.jpg
  public/assets/images/haras.jpg
  src/View/User/Includes/_carousel.html.twig
  src/View/User/course.html.twig
Labels: Conflicts Resolved, Reviewed

#44 connecting with pages
  public/assets/css/navbar.css
  src/View/Includes/_navbar.html.twig
Labels: Corrections done, Reviewed

#50 add white text in contact page
  public/assets/css/contact.css
  public/assets/css/contact_white_block.css
  src/View/User/Includes/_contact_white_block.html.twig
  src/View/User/contact.html.twig
Labels: Corrections done, Reviewed

#49 add white block in stage page
  public/assets/css/stage.css
  public/assets/css/stage_white_block.css
  src/View/User/Includes/_stage_white_block.html.twig
  src/View/User/stage.html.twig
Labels: Corrections done, Reviewed

#51 removed absolute carousel.css
  public/assets/css/carousel.css
Labels: Reviewed

#41 US03 05 banner and text haras on Accueil
  src/View/User/course.html.twig
  src/View/User/haras.html.twig
Labels: Conflicts Resolved, Reviewed

#42 Us04 04 banner and text cours
  src/View/User/course.html.twig
Labels: Resolved conflict, Reviewed

#54 change class css hover
  public/assets/css/navbar.css
Labels: Reviewed

#55 Insert banner and title in Stages
  src/View/User/stage.html.twig
Labels: Reviewed

#60 resolve position for presentation in bootstrap
  src/View/User/Includes/_carousel.html.twig
Labels: Reviewed

#59 css homepage
  public/assets/css/welcome.css
  src/View/Home/index.html.twig
  src/View/User/Includes/_welcome_background_slideshow.html.twig
Labels: Reviewed

#56 change last class btn
  public/assets/css/navbar.css
Labels: Reviewed

#61 repare slide button
  src/View/Includes/_button_to_go_up.html.twig
Labels: Corrections done, Reviewed

#62 links footer
  src/View/Includes/_footer.html.twig
Labels: Reviewed

#63 correctifs
  src/View/Includes/_button_to_go_up.html.twig
  src/View/Includes/_footer.html.twig
Labels: Reviewed

#64 refactor twig layout
  src/View/Admin/course.html.twig
  src/View/Admin/layout_admin.html.twig
  src/View/Home/index.html.twig
  src/View/User/contact.html.twig
  src/View/User/course.html.twig
  src/View/User/haras.html.twig
  src/View/User/layout_user.html.twig
  src/View/User/stage.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#71 change color of button formulary to respect colors of site
  public/assets/css/admin.css
  public/assets/css/admin_formulary.css
Labels: Reviewed

#75 course.sql with create and insert for test
  course.sql
Labels: Corrections done, Reviewed

#77 ajout formulaire de base pour utilisateur inscription cours
  public/assets/css/course_inscription_form.css
  src/Controller/CourseFormController.php
  src/View/User/Includes/_inscription_form_course.html.twig
  src/View/User/course_form.html.twig
Labels: Corrections done, Reviewed

#81 add an admin page to handle inscription to courses
  src/Controller/AdminCourseInscriptionController.php
  src/View/Admin/course_inscription.html.twig
Labels: Reviewed

#69 create formulary and change controller name for future
  src/Controller/AdminController.php
  src/Controller/AdminCourseController.php
  src/View/Admin/Includes/_formulary_course.html.twig
  src/View/Admin/course.html.twig
Labels: Resolved conflict

#73 Resolve #71
  src/View/Admin/Includes/_navbar.html.twig
Labels: Reviewed

#80 Ajouts bases de données Parents et pupils
  parent.sql
  pupil.sql
Labels: Reviewed

#84 resolve
  src/View/Admin/layout_admin.html.twig
Labels: Reviewed

#85 create manager and connect to insert
  src/Controller/AdminCourseController.php
  src/Model/CourseManager.php
Labels: Reviewed

#92 changing done
  course.sql
  src/View/Admin/Includes/_formulary_course.html.twig
Labels: Reviewed

#93 Us21 04 show course in admin course
  public/assets/css/admin.css
  public/assets/css/admin_course_show.css
  src/Controller/AdminCourseController.php
  src/View/Admin/Includes/_show_courses.html.twig
  src/View/Admin/course.html.twig
Labels: Reviewed

#94 ajout de la securisation du formulaire
  public/assets/css/course_tab.css
  src/Controller/CourseFormController.php
  src/View/User/Includes/_course_tab.html.twig
  src/View/User/Includes/_inscription_form_course.html.twig
Labels: Reviewed

#100 fix navbar+background
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/font/Bellerose.ttf
  src/View/Includes/_navbar.html.twig
Labels: Reviewed

#98 editing course admin
  src/Controller/AdminCourseController.php
  src/Model/CourseManager.php
  src/View/Admin/Includes/_formulary_course.html.twig
  src/View/Admin/Includes/_show_courses.html.twig
Labels: Corrections done, Question answered, Reviewed

#101 delete course
  src/Controller/AdminCourseController.php
  src/View/Admin/Includes/_show_courses.html.twig
Labels: Reviewed

#102 Database lié au formulaire
  parent.sql
  pupil.sql
  src/Controller/CourseFormController.php
  src/Model/ParentManager.php
  src/Model/PupilManager.php
Labels: Reviewed

#90 add Form Inscription Stages
  public/assets/css/stages_inscription.css
  src/Controller/StagesInscriptionsController.php
  src/View/User/Includes/_inscription_form_stages.html.twig
  src/View/User/stages_form_inscription.html.twig
Labels: Corrections done, Reviewed

#103 ajout navbar admin pour inscription cours
  public/assets/css/navbar.css
  src/View/Admin/Includes/_navbar.html.twig
Labels: Reviewed

#105 relation admin / user for btn courses
  course.sql
  src/Controller/CourseController.php
  src/Model/CourseManager.php
  src/View/User/Includes/_course_tab.html.twig
Labels: Reviewed

#107 Resolve #106
  public/assets/css/admin_course_show.css
  src/Controller/AdminCourseController.php
  src/Model/CourseManager.php
  src/View/Admin/Includes/_formulary_course.html.twig
  src/View/Admin/Includes/_show_courses.html.twig
Labels: Reviewed

#109 mise en page cours
  public/assets/css/carousel.css
  public/assets/css/course.css
  public/assets/css/course_tab.css
  public/assets/css/course_white_block.css
  public/assets/images/faceharas.jpg
  public/assets/images/poneycarousel.jpg
  public/assets/images/prairieharas.jpg
  src/View/User/Includes/_carousel.html.twig
  src/View/User/Includes/_course_tab.html.twig
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/course.html.twig
Labels: Reviewed

#111 mise en page de la page stage
  public/assets/css/stage.css
  public/assets/css/stage_grey_block.css
  public/assets/css/stage_white_block.css
  src/View/User/Includes/_stage_grey_block.html.twig
  src/View/User/Includes/_stage_white_block.html.twig
  src/View/User/stage.html.twig
Labels: Reviewed

#83 Us23 01 form contact
  .gitignore
  public/assets/css/contact.css
  public/assets/css/contact_grey_block.css
  public/assets/css/haras_grey_block.css
  src/View/User/Includes/_contact_grey_block.html.twig
  src/View/User/contact.html.twig
Labels: Resolved conflict

#108 New tables for Stages
  course.sql
  parent.sql
Labels: Resolved conflict

#115 change readme
  README.md
Labels: Reviewed

#113 add stage carousel and image carousel adaptative
  public/assets/images/stage1.jpg
  public/assets/images/stage2.jpg
  public/assets/images/stage3.jpg
  src/Controller/CourseController.php
  src/Controller/StageController.php
  src/View/User/Includes/_carousel.html.twig
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/Includes/_stage_white_block.html.twig
Labels: Corrections done, Reviewed

#116 Course form select
  src/Controller/CourseFormController.php
  src/View/User/Includes/_inscription_form_course.html.twig
Labels: Reviewed

#114 Add resultats formulaires sur admin cours
  public/assets/css/admin.css
  public/assets/css/admin_course_inscription.css
  src/Controller/AdminCourseInscriptionController.php
  src/Model/PupilManager.php
  src/View/Admin/Includes/_show_courses_inscription.html.twig
  src/View/Admin/course_inscription.html.twig
Labels: Reviewed

#118 Us20 04 mise en page contact
  public/assets/css/contact.css
  public/assets/css/contact_grey_block.css
  public/assets/css/contact_white_block.css
  src/View/User/Includes/_contact_grey_block.html.twig
  src/View/User/Includes/_contact_white_block.html.twig
  src/View/User/contact.html.twig
Labels: Reviewed

#121 fix method form
  src/View/User/Includes/_contact_grey_block.html.twig
Labels: Reviewed

#125 changements lorem page 1-3
  public/assets/css/haras_white_block.css
  public/assets/css/welcome.css
  src/View/User/Includes/_course_tab.html.twig
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/Includes/_haras_grey_block.html.twig
  src/View/User/Includes/_haras_white_block.html.twig
  src/View/User/Includes/_welcome_background_slideshow.html.twig
Labels: Reviewed

#123 fix terminal bug
  course.sql
Labels: Reviewed

#124 change banner for all pages
  public/assets/images/banner.jpg
  public/assets/images/banner_course.webp
  src/View/User/course.html.twig
  src/View/User/haras.html.twig
  src/View/User/stage.html.twig
Labels: Corrections done, Reviewed

#128 spacing carousel
  src/View/User/Includes/_carousel.html.twig
Labels: Reviewed

#127 fix bug grey block haras
  public/assets/css/haras_grey_block.css
Labels: Reviewed

#129 fix bug grey block haras
  src/View/User/Includes/_haras_grey_block.html.twig
Labels: Reviewed

#130 fix_db
  README.md
  db.sql
  parent.sql
  pupil.sql
Labels: Reviewed

#131 last S03
  README.md
  db.sql
  parent.sql
  public/assets/css/haras_grey_block.css
  public/assets/css/haras_white_block.css
  public/assets/css/welcome.css
  public/assets/images/banner.jpg
  public/assets/images/banner_course.webp
  pupil.sql
  src/View/User/Includes/_carousel.html.twig
  src/View/User/Includes/_contact_grey_block.html.twig
  src/View/User/Includes/_course_tab.html.twig
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/Includes/_haras_grey_block.html.twig
  src/View/User/Includes/_haras_white_block.html.twig
  src/View/User/Includes/_welcome_background_slideshow.html.twig
  src/View/User/course.html.twig
  src/View/User/haras.html.twig
  src/View/User/stage.html.twig
Labels: Reviewed
