Repository WildCodeSchool/orleans-php-202103-project-haras, pull requests merged in 2021-05, with the labels that each got.

#132 Bouton delete des inscriptions aux cours
  src/Controller/AdminCourseInscriptionController.php
  src/View/Admin/Includes/_show_courses_inscription.html.twig
Labels: Reviewed

#133 create calendar courses
  public/assets/css/course.css
  src/Controller/CourseController.php
  src/Service/Sort.php
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/Includes/_show_courses.html.twig
Labels: Reviewed

#135 fix bug bool experience form course inscription
  src/Controller/CourseFormController.php
Labels: Reviewed

#112 S03 us27 03 formulary security stages
  public/assets/css/stages_inscription.css
  src/Controller/StageFormController.php
  src/Controller/StagesInscriptionsController.php
  src/View/User/Includes/_inscription_form_course.html.twig
  src/View/User/Includes/_inscription_form_stages.html.twig
Labels: Corrections done, Reviewed

#139 connect with Sort::class
  src/Controller/AdminCourseController.php
  src/Controller/CourseFormController.php
Labels: Reviewed

#144 add helpers
  src/View/Admin/Includes/_formulary_course.html.twig
Labels: Reviewed

#142 fix
  src/View/User/Includes/_contact_white_block.html.twig
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/Includes/_stage_white_block.html.twig
Labels: Reviewed

#140 Resolve #137
  public/assets/css/haras.css
  public/assets/css/haras_googlemap.css
  public/assets/css/haras_white_block.css
  src/View/User/Includes/_haras_googlemap.html.twig
  src/View/User/Includes/_haras_white_block.html.twig
Labels: Reviewed

#136 S04 us35 02 edit admin form course inscription
  src/Controller/AdminCourseInscriptionController.php
  src/Controller/CourseFormController.php
  src/Model/ParentManager.php
  src/Model/PupilManager.php
  src/View/Admin/Includes/_show_courses_inscription.html.twig
  src/View/User/Includes/_inscription_form_course.html.twig
Labels: Conflicts Resolved, Reviewed

#145 ajout table stage
  db.sql
Labels: Reviewed

#146 add Button link
  public/assets/css/stage_grey_block.css
  src/View/User/Includes/_stage_grey_block.html.twig
Labels: Reviewed

#150 add closed div
  src/View/User/Includes/_stage_grey_block.html.twig
Labels: Reviewed

#151 ajustement des DB
  db.sql
Labels: Corrections done, Reviewed

#152 form stage + securisation
  src/Controller/AdminStageController.php
  src/View/Admin/Includes/_formulary_stage.html.twig
  src/View/Admin/Includes/_navbar.html.twig
  src/View/Admin/stage.html.twig
Labels: Reviewed

#153 add insert db
  src/Controller/AdminStageController.php
  src/Model/StageManager.php
Labels: Reviewed

#154 Ajout demande cours admin
  src/Controller/AdminCourseInscriptionController.php
  src/Controller/CourseFormController.php
  src/Model/CoursingManager.php
  src/Model/PupilManager.php
  src/View/Admin/Includes/_show_courses_inscription.html.twig
  src/View/User/Includes/_inscription_form_course.html.twig
Labels: Reviewed

#155 S04 us35 04 fix edit admin form course
  src/Controller/AdminCourseInscriptionController.php
  src/Controller/CourseFormController.php
  src/Model/CoursingManager.php
  src/Model/PupilManager.php
  src/View/User/Includes/_inscription_form_course.html.twig
Labels: Reviewed

#161 use cascade
  db.sql
Labels: Reviewed

#158 add delete
  src/Controller/AdminStageController.php
Labels: Reviewed

#159 first commit
  src/Controller/AdminStageInscriptionController.php
  src/Controller/StageFormController.php
  src/Model/PupilManager.php
  src/Model/StagingManager.php
  src/View/Admin/Includes/_navbar.html.twig
  src/View/Admin/Includes/_show_stage_inscription.html.twig
  src/View/Admin/stage_inscription.html.twig
  src/View/User/Includes/_inscription_form_stages.html.twig
Labels: Reviewed

#157 Us 33 05 add update
  src/Controller/AdminStageController.php
  src/Model/StageManager.php
  src/View/Admin/Includes/_show_stages.html.twig
  src/View/Admin/stage.html.twig
Labels: Conflicts Resolved, Reviewed

#164 add satges in table
  src/Controller/AdminStageController.php
Labels: Reviewed

#163 Fix page accueil
  public/assets/css/welcome.css
  src/View/User/Includes/_welcome_background_slideshow.html.twig
Labels: Reviewed

#167 add button admin -> User
  src/View/Admin/Includes/_navbar.html.twig
Labels: Reviewed

#169 Add Delete Admin Form Stage
  src/Controller/AdminStageInscriptionController.php
  src/View/Admin/Includes/_show_stage_inscription.html.twig
Labels: Reviewed

#168 fix coursecontroller 1st method = string
  src/Controller/CourseController.php
Labels: Reviewed

#166 Button edit
  src/Controller/AdminCourseInscriptionController.php
  src/Controller/AdminStageInscriptionController.php
  src/Model/PupilManager.php
  src/Model/StageManager.php
  src/View/Admin/Includes/_show_stage_inscription.html.twig
  src/View/User/Includes/_inscription_form_stages.html.twig
Labels: Conflicts Resolved, Reviewed

#170 US23_forms
  public/assets/css/contact_grey_block.css
  src/Controller/ContactController.php
  src/View/User/Includes/_contact_grey_block.html.twig
Labels: Corrections done, Reviewed

#171 Lorem ipsum stage page
  src/View/User/Includes/_stage_grey_block.html.twig
  src/View/User/Includes/_stage_white_block.html.twig
Labels: Reviewed

#188 Resolve #173 size show table course
  public/assets/css/course.css
Labels: Reviewed

#190 fix novalidate
  src/View/User/Includes/_inscription_form_stages.html.twig
Labels: Reviewed

#191 Fix Orthographes
  src/View/User/Includes/_haras_white_block.html.twig
  src/View/User/Includes/_welcome_background_slideshow.html.twig
Labels: Reviewed

#192 Fix Button Inscription
  public/assets/css/course_tab.css
  public/assets/css/stage_grey_block.css
  src/View/User/Includes/_stage_grey_block.html.twig
Labels: Reviewed

#193 add service
  src/Controller/AdminCourseInscriptionController.php
  src/Controller/AdminStageInscriptionController.php
  src/Controller/CourseFormController.php
  src/Controller/StageFormController.php
  src/Service/MinimumAge.php
Labels: Reviewed

#197 Fix Style et texte
  public/assets/css/course_inscription_form.css
  src/View/User/Includes/_haras_grey_block.html.twig
  src/View/User/Includes/_inscription_form_stages.html.twig
Labels: Reviewed

#198 add helper
  src/View/Admin/Includes/_formulary_stage.html.twig
Labels: Reviewed

#196 navbar admin
  src/Controller/AdminCourseInscriptionController.php
  src/Controller/AdminStageInscriptionController.php
  src/View/Admin/course_form.html.twig
  src/View/Admin/layout_admin.html.twig
  src/View/Admin/stages_form_inscription.html.twig
Labels: Reviewed

#195 Fix lorem ipsum page contact
  src/View/User/Includes/_contact_white_block.html.twig
Labels: Reviewed

#194 fix contact in grey block
  public/assets/css/contact_grey_block.css
  src/View/User/Includes/_contact_grey_block.html.twig
Labels: Conflicts Resolved, Reviewed

#200 age modified in cours
  src/View/User/Includes/_course_tab.html.twig
Labels: Reviewed

#202 Modif Title Css ans Text Stages
  public/assets/css/stage.css
  src/View/User/Includes/_stage_grey_block.html.twig
  src/View/User/Includes/_stage_white_block.html.twig
Labels: Reviewed

#201 Fix Form Inscription
  src/Controller/AdminCourseInscriptionController.php
  src/Controller/AdminStageInscriptionController.php
  src/Controller/CourseFormController.php
  src/Controller/StageFormController.php
  src/Model/PupilManager.php
  src/View/User/Includes/_inscription_form_course.html.twig
  src/View/User/Includes/_inscription_form_stages.html.twig
Labels: Reviewed

#205 resolve class form
  src/View/User/Includes/_contact_grey_block.html.twig
Labels: Reviewed

#206 responsive mobile
  src/View/User/Includes/_show_stages.html.twig
Labels: Reviewed

#189 delete /br or change to p
  src/View/User/Includes/_course_tab.html.twig
  src/View/User/Includes/_haras_white_block.html.twig
  src/View/User/Includes/_show_courses.html.twig
  src/View/User/Includes/_welcome_background_slideshow.html.twig
Labels: Conflicts Resolved, Reviewed

#203 add condition in service
  src/Service/MinimumAge.php
Labels: Reviewed

#199 orthograph modif
  src/View/User/Includes/_contact_white_block.html.twig
Labels: Corrections done, Reviewed

#204 forms contact fixed
  src/Controller/ContactController.php
  src/View/User/Includes/_contact_grey_block.html.twig
Labels: Corrections done, Reviewed

#207 Fix span text
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/Includes/_haras_white_block.html.twig
  src/View/User/Includes/_stage_white_block.html.twig
Labels: Reviewed

#208 Img Poney
  src/View/User/Includes/_course_tab.html.twig
Labels: Reviewed

#209 xl bootstrap
  src/View/User/Includes/_course_tab.html.twig
Labels: Reviewed

#210 changement bannieres
  public/assets/images/bannercourse.jpg
  public/assets/images/bannerharas.jpg
  public/assets/images/bannerstage.jpg
  src/View/User/course.html.twig
  src/View/User/haras.html.twig
  src/View/User/stage.html.twig
Labels: Reviewed

#211 css
  public/assets/css/banner.css
  public/assets/css/contact.css
  public/assets/css/contact_googlemap.css
  public/assets/css/contact_grey_block.css
  public/assets/css/contact_white_block.css
  public/assets/css/course.css
  public/assets/css/course_tab.css
  public/assets/css/footer.css
  public/assets/css/haras.css
  public/assets/css/haras_grey_block.css
  public/assets/css/haras_white_block.css
  public/assets/css/stage.css
  public/assets/css/stage_grey_block.css
  public/assets/css/style.css
  src/View/User/Includes/_carousel.html.twig
  src/View/User/Includes/_contact_grey_block.html.twig
Labels: Resolved conflict, Reviewed

#212 fix footer
  public/assets/css/haras_grey_block.css
  src/View/User/Includes/_haras_grey_block.html.twig
Labels: Reviewed

#214 Fix span css
  public/assets/css/course_white_block.css
  public/assets/css/haras_white_block.css
  public/assets/css/stage_white_block.css
  src/View/User/Includes/_stage_white_block.html.twig
Labels: Corrections done, Reviewed

#215 responsive stage
  public/assets/css/stage_white_block.css
  src/View/Admin/Includes/_formulary_course.html.twig
  src/View/Admin/Includes/_formulary_stage.html.twig
  src/View/User/Includes/_stage_white_block.html.twig
Labels: Reviewed

#216 Finish project 2
  public/assets/css/banner.css
  public/assets/css/contact.css
  public/assets/css/contact_googlemap.css
  public/assets/css/contact_grey_block.css
  public/assets/css/contact_white_block.css
  public/assets/css/course.css
  public/assets/css/course_inscription_form.css
  public/assets/css/course_tab.css
  public/assets/css/course_white_block.css
  public/assets/css/footer.css
  public/assets/css/haras.css
  public/assets/css/haras_grey_block.css
  public/assets/css/haras_white_block.css
  public/assets/css/stage.css
  public/assets/css/stage_grey_block.css
  public/assets/css/stage_white_block.css
  public/assets/css/style.css
  public/assets/images/bannercourse.jpg
  public/assets/images/bannerharas.jpg
  public/assets/images/bannerstage.jpg
  src/Controller/AdminCourseInscriptionController.php
  src/Controller/AdminStageInscriptionController.php
  src/Controller/ContactController.php
  src/Controller/CourseFormController.php
  src/Controller/StageFormController.php
  src/Model/PupilManager.php
  src/Service/MinimumAge.php
  src/View/Admin/Includes/_formulary_course.html.twig
  src/View/Admin/Includes/_formulary_stage.html.twig
  src/View/Admin/course_form.html.twig
  src/View/Admin/layout_admin.html.twig
  src/View/Admin/stages_form_inscription.html.twig
  src/View/User/Includes/_carousel.html.twig
  src/View/User/Includes/_contact_grey_block.html.twig
  src/View/User/Includes/_contact_white_block.html.twig
  src/View/User/Includes/_course_tab.html.twig
  src/View/User/Includes/_course_white_block.html.twig
  src/View/User/Includes/_haras_grey_block.html.twig
  src/View/User/Includes/_haras_white_block.html.twig
  src/View/User/Includes/_inscription_form_course.html.twig
  src/View/User/Includes/_inscription_form_stages.html.twig
  src/View/User/Includes/_show_courses.html.twig
  src/View/User/Includes/_show_stages.html.twig
  src/View/User/Includes/_stage_grey_block.html.twig
  src/View/User/Includes/_stage_white_block.html.twig
  src/View/User/Includes/_welcome_background_slideshow.html.twig
  src/View/User/course.html.twig
  src/View/User/haras.html.twig
  src/View/User/stage.html.twig
Labels: Reviewed
